# Generated by Django 4.2.10 on 2025-06-25 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
