# Generated by Django 4.2.10 on 2025-06-27 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_student_marks_remove_student_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='marks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
